### ISSUE TITLE
"Another Player casts his/her lot <item>" messages not being filtered.

### ISSUE THREAD

**Issue by Xiniox** [NadyaNayme/TidyChat#94]
![image](https://github.com/user-attachments/assets/6c13de25-3824-454b-882c-8cdfa161ef73)

I have my settings set up like this, but I still get all the messages whenever people roll on an item. It's been like this since after the 7.1 update. Is there a setting I'm missing somewhere or is it broken?

**Comment by explosive-bunny** [comment]
Also reporting that I'm having this issue too around the same timeframe. Noticed it was still happening even after I reinstalled on a new PC

**Comment by NadyaNayme** [comment]
It looks like I had two rules using the same setting instead of each using their own setting - due to bad copy/paste coding.

The `ShowOthersLootRoll` was also being used for the `HideOthersObtain` rule by accident that was checking for `OtherObtains`. This was causing it to _match_ the first rule (the one it is meant to match) and show the message and then check the message again and _fail to match_ because it was checking the wrong regex. Once it failed to match the rule instead of being blocked it was being allowed to pass through.

I did not have time to test it - sadly I never do anymore - but the logic I was seeing and fixed makes sense as to why this message would be showing. With the `HideOthersObtain` now properly using its own setting both settings should now work as expected. 

This should be fixed when the PR for 2.0.12 is merged - which I'm writing up right after this.

**Comment by Xiniox** [comment]
Currently using 2.0.12 and the messages are still showing unfortunately D:

**Comment by Kagekazu** [comment]
should be fixed next update

**Comment by Kagekazu** [comment]
Fixed in V2.3.1.0
